### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by merolaika** [danivs10/Automatic-Video-Generator-for-youtube#1]
Hello, i get this error; 

```
Traceback (most recent call last):
  File "Automatic-Video-Generator-for-youtube\main.py", line 7, in <module>
    topic = sys.argv[1]
IndexError: list index out of range
```

**Comment by danivs10** [comment]
You need to write an argument when calling the main.py file indicating the topic of the video. An example could be: python main.py "Roman empire". Let me add a readme to the repo so everything is clearer. :) Thank you for your feedback, I hope you like the repo, and if you have any suggestion or improvement feel free to add it!
